project:
  type: default
  output-dir: docs/
  resources:
    - reports/*_files/

format:
  hugo-md:
    variant: +yaml_metadata_block
    toc: true
    number-sections: false
    html-math-method: mathjax
    code-fold: true
    code-summary: "Show code"
    fig-width: 8
    fig-height: 6
    filters:
      - _extensions/filters/hugo-figures.lua
    keep-md: false
  html:
    number-sections: false
    html-math-method: mathjax
    code-fold: true
    code-summary: "Show code"
    fig-width: 8
    fig-height: 6
  typst:
    toc: true
    number-sections: false
    fig-width: 8
    fig-height: 6
    papersize: a4

execute:
  echo: false
  warning: false
  message: false
  freeze: auto
