name: Archive meetup data

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  meetup:
    name: Archive meetup data
    runs-on: ubuntu-latest
    env:
      meetupr_jwt_token: ${{ secrets.JWT_TOKEN }}
      meetupr_jwt_issuer: ${{ secrets.JWT_ISSUER }}
      meetupr_client_key: ${{ secrets.CLIENT_KEY }}
      RENV_PATHS_ROOT: ~/.cache/R/renv
      RENV_PROFILE: archive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libsecret-1-dev libx11-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"
          use-public-rspm: true

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Meetup authentication status
        run: Rscript -e "meetupr::meetup_sitrep()"

      - name: Archive all meetup data
        run: Rscript scripts/archive_all.R

      - name: Update website data
        run: Rscript scripts/data_prep_website.R

      - name: Commit data
        if: github.event_name == 'schedule' || github.event_name == 'push'
        run: |
          git config --local user.email "actions@github.com"	
          git config --local user.name "GitHub Actions"	
          git add data/	archive/
          git commit -m 'Update meetup data' || echo "No meetup data to commit"	
          git push || echo "Nothing to push"
